### ISSUE TITLE
Refactor all `TestDataGenerator` methods to use `Persona`

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#102]
Follow the pattern introduced by `generateProtocolsConfigureMessage` and `generateProtocolsQueryMessage`.

**Comment by nearlyjuly** [comment]
I can have a go if I can have some instructions

**Comment by thehenrytsai** [comment]
Thanks @nearlyjuly, the idea is to follow the usage pattern or `Persona` introduced by generateProtocolsConfigureMessage and generateProtocolsQueryMessage and change all generateXyzMessage() methods. Essentially combining 3 arguments into 1.

**Comment by Cxxshyy** [comment]
hi @thehenrytsai i dont know if he has done this yet but could you expand on how i could carry this out

**Comment by nearlyjuly** [comment]
About halfway through but no problem at all if you complete it first.

**Comment by Cxxshyy** [comment]
hey no problem i just wasn't sure if you were working on it but if you are i'll leave you to it

**Comment by nearlyjuly** [comment]
This is what I have so far https://github.com/TBD54566975/dwn-sdk-js/pull/114 not sure whether requesterDidMethod needs to be kept

**Comment by thehenrytsai** [comment]
@nearlyjuly, I'd say you can get rid off `requesterDidMethod`. There is only one use of it, so we can replace that by using `getDidMethodName()` directly.

**Comment by thehenrytsai** [comment]
Merged.
