### ISSUE TITLE
refactor code to use encoding methods in `encoder.ts`

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#109]
Refactor the entire codebase to use encoding methods in [`encoder.ts`](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/utils/encoder.ts) as opposed to directly referencing underlying dependencies/libraries. This allows us swap out implementation if needed.

See example usage in [`signer.ts`](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/jose/jws/general/signer.ts#L3)

**Comment by Cxxshyy** [comment]
Hi again could i get a little explanation on how this could be carried out as well

**Comment by Cxxshyy** [comment]
to be more specific the files that would need to be refactored

**Comment by Cxxshyy** [comment]
#115 attempts to tackle this issue

**Comment by thehenrytsai** [comment]
@Cxxshyy, thanks for the contribution!! What you did is exactly what the issue was intended. There is still the replacement for new TextEncoder().encode(...) occurrences, but did not hold #115 for it, approved and merged it.

**Comment by Cxxshyy** [comment]
like i said before i'll take a look tomorrow at this encoder

**Comment by Cxxshyy** [comment]
@thehenrytsai pr #116 looks to implement a new feature and hopefully solves the new TextEncoder().encode(...) occurrences issue
