### ISSUE TITLE
Implement Hooks

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dwn-sdk-js#11]
related proposal issue: decentralized-identity/identity-hub#127

**Comment by pdxjohnny** [comment]
What is meant by this? Does websub make sense to build off here? How can one help?

- https://github.com/w3c/websub/tree/master/implementation-reports
  - https://github.com/marten-de-vries/Flask-WebSub
  - Publisher client with Verifiable Credentials and Credential Manifests
    - https://identity.foundation/credential-manifest/#credential-requirement-discovery
    - A Verifiable Credential is then issued
      - https://w3c-ccg.github.io/traceability-vocab/#BillOfLadingCredential
      - https://w3c-ccg.github.io/traceability-vocab/openapi/components/schemas/credentials/BillOfLadingCredential.yml
      - https://w3c-ccg.github.io/traceability-vocab/openapi/components/schemas/common/BillOfLading.yml

**Comment by thehenrytsai** [comment]
Closing until revisit is needed again.
