### ISSUE TITLE
Change `dateCreated` descriptor property from epoch time to higher precision format

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#113]
Requirements:
1. Adopt ISO 8601 UTC format with microsecond precision enforcement, disallowing timezone selector (even 'Z'):
   `2022-10-14T10:20:30.405060` would be an accepted string.
   `2022-10-14T10:20:30.405060Z` would NOT be an accepted string.
   `2022-10-14T10:20:30.405` would NOT be an accepted string.

This allows us to compare time using a direct string compare.

**Comment by csuwildcat** [comment]
Can we even get microsecond on all platforms/envs? I guess you'd just write in 0s if not, right?

**Comment by thehenrytsai** [comment]
Pretty sure all modern machine can get microsecond precision, if not implementor can either fill with 0s, or random generate 3 digits.

**Comment by rajakash-dev** [comment]
Have a doubt , the current format is number and all comparisons happen with the same but to support format like `2022-10-14T10:20:30.405060` we will have to convert the usage of `dateCreated ` everywhere from number to string .Is this expected as a part of this feature?

**Comment by thehenrytsai** [comment]
@rajakash-dev, yes you are correct, that's the change

**Comment by rajakash-dev** [comment]
https://github.com/TBD54566975/dwn-sdk-js/pull/142

**Comment by thehenrytsai** [comment]
@csuwildcat, please update DWN spec accordingly.

**Comment by csuwildcat** [comment]
Will do
