### ISSUE TITLE
Can't make dwn-sdk-js working with "jest"

### ISSUE THREAD

**Issue by subuta** [TBD54566975/dwn-sdk-js#119]
> Cannot find module '@tbd54566975/dwn-sdk-js' from 'src/__tests__/index.test.ts'

when I run `npm test` with jest, got the error above. Can someone points me how to make this working with `jest`?
I already tried `--es-module-specifier-resolution=node` from #107, but no luck with jest, while applying same option to `ts-node` runs without any error 🤔 

Here are the minimum reproduction of this issue. try running `npm i & npm test` will result the error above.

https://github.com/subuta/dwn-sdk-js-jest-issue/blob/main/package.json#L23

## Environment

- macOS Big Sur v11.6
- Node.js v18.11.0

- jest@29.2.1
- ts-jest@29.0.3

**Comment by thehenrytsai** [comment]
We use `mocha` as the test framework. Any reason why you are attempting to use `jest`?

**Comment by subuta** [comment]
> We use mocha as the test framework. Any reason why you are attempting to use jest?

@thehenrytsai Thanks for your reply. Yeah, For web application development, I frequently uses jest. and interested to know if `dwn-sdk-js` are also works well with jest or not. Have you tried jest with this project(dwn-sdk-js) in the past? Establishing configuration for pairing with jest would be helpful for other developers like me.

**Comment by thehenrytsai** [comment]
Hi @subuta, no I have not tried jest. But using mocha should not preclude the usage of this library from being used for web development in "theory".

`npm run test:browser` in fact spins up a headless browser to run all the tests.

On a related note, I am aware of the popularity of jest in recent years and open to switch over to jest if that's gonna help with contribution and adoption, but would need help porting all the tests over!

**Comment by subuta** [comment]
@thehenrytsai Yeah. I was used `mocha & karma` configuration in the past, and it should work well for web development, of course 👍 . As you noted, We can find a lot of project use `jest` for both Node.js(testEnvironment: 'node') and browser(testEnvironment : 'jsdom'). and make `dwn-sdk-js` working with `jest` would profit many developers.

The problem I stated above were related to how this project were distributed (ESM). 
I'm not sure about root cause, but `jest` has own module resolution logic AFAIK, and that triggers hard to debug error like `Cannot find module '@tbd54566975/dwn-sdk-js' from 'src/tests/index.test.ts'` by some reason.

One possible solution would be change distribution style of this module(dwn-sdk-js) to make it understandable by jest, eg: distrubute it as CJS, or find a workaround with current distribution style(`tsc` transpiled ESM files). https://github.com/TBD54566975/dwn-sdk-js/blob/main/package.json#L28

**Comment by thehenrytsai** [comment]
@subuta, thanks for the feedback, we fixed a few browser compatibility issues with our published package. [v0.0.10](https://www.npmjs.com/package/@tbd54566975/dwn-sdk-js/v/0.0.10) should now be useable, are you able to sanity verify? Thanks!!

**Comment by subuta** [comment]
@thehenrytsai Updating package to `v0.0.10` by running `npm i @tbd54566975/dwn-sdk-js@v0.0.10` resolved `Cannot find module '@tbd54566975/dwn-sdk-js' from 'src/tests/index.test.ts'` issue, Many thanks 👍 .

For the future readers, I had to use following `jest.config.js` for jest to transpile `@tbd54566975/dwn-sdk-js` (ESM package) properly for executing tests

https://github.com/subuta/dwn-sdk-js-jest-issue/blob/main/jest.config.js

```jsx
/** @type {import('ts-jest').JestConfigWithTsJest} */

// Modules needs transpile.
const es6Modules = [
  "@tbd54566975/dwn-sdk-js"
]

export default {
  preset: 'ts-jest/presets/js-with-ts-esm',
  testEnvironment: 'node',
  transformIgnorePatterns: [`node_modules/(?!${es6Modules.join("|")})`],
  testPathIgnorePatterns: [
    '/node_modules/',
    '<rootDir>/dist'
  ]
};
```

**Comment by thehenrytsai** [comment]
Closing, let us know if another related issue pops up!
