### ISSUE TITLE
Retain record inception/lineage to strengthen determinism of correct lineage

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#125]
In order to prevent record hijacking, we should retain the inception record and likely some other checkpoint-ish record instances over the history of a record, that can be used to deterministically evaluate which is the correct tip state.

**Comment by thehenrytsai** [comment]
Implemented by https://github.com/TBD54566975/dwn-sdk-js/commit/79ce876e62c4c1c72968bf83325c6cac87c7abc1
