### ISSUE TITLE
Why does line 110 of message-level-store.ts work on main branch

### ISSUE THREAD

**Issue by Cxxshyy** [TBD54566975/dwn-sdk-js#132]
"""const { RESULT: indexResults } = await this.index.QUERY(finalQuery);"""
this is the code on line 110 of the file mentioned however the query function expects a token then an optional options arg
"""QUERY(query: Token, options?: QueryOptions): Promise<QueryResult>;"""
so right now my code wont test due to this error:

src/store/message-store-level.ts:111:61
 - error TS2345: Argument of type '{ NOT: { INCLUDE: { AND: SearchIndexTerm[]; }; EXCLUDE: { AND: SearchIndexTerm[]; }; }; }' is not assignable to parameter of type 'Token'.

111     const { RESULT: indexResults } = await this.index.QUERY(finalQuery);

**Comment by thehenrytsai** [comment]
I think you pulled the source code recently, but did not `npm install` after, there was an update to type dependencies recently.

**Comment by Cxxshyy** [comment]
ah yes that was the reason my apologies

**Comment by thehenrytsai** [comment]
No worries! It happens to all of us! 😆
