### ISSUE TITLE
Increase code coverage (even if just by a little bit)

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#136]
### Background:
The code coverage goal is 100% for this repo, so any PR adding any test to increase the overall code coverage would be super useful!

### Task Details:
To know what code hasn't been covered:
1. Run `npm run test:node`
2. Ignore the code coverage summary at the end of the run, there is a better way:
3. Use MacOS Finder or Windows Explorer to open the `coverage/index.html` page, it will show you precisely what line of code is not covered

Files that can be ignored as they will likely be undergoing drastic changes:
- `permissions-request.ts`

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by tux7P** [comment]
picking this up

**Comment by EbonyLouis** [comment]
@tux7P Yay! I'll assign it to you now.

 I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [is now open.](https://hacktoberfest.com/auth/) Reach out if you need any help 🥳 

Good Luck 🍁

**Comment by EbonyLouis** [comment]
More than one person can work on this issue, feel free to comment "picking this up" if it interest you! 🍁

**Comment by shobitb** [comment]
@EbonyLouis, picking this up!

**Comment by EbonyLouis** [comment]
Heyy @tux7P how are things going with this issue? Is this something you still want to work on?

**Comment by Tushar98644** [comment]
@EbonyLouis picking this up !

**Comment by ANIRUDH-333** [comment]
picking this up

**Comment by ANIRUDH-333** [comment]
.take

**Comment by ANIRUDH-333** [comment]
Can I still pick this up? @EbonyLouis

**Comment by EbonyLouis** [comment]
@ANIRUDH-333, yes! I just assigned it to you thank you for contributing ✨
