### ISSUE TITLE
Automatic version bump to `package.json` every time a PR is merged into `main` unless an override is given

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#137]
Proposing the following version format:
`<sem-ver>-unstable-YYYYMMDD-<increment>`

e.g.
`0.0.10-unstable-20221031-1`

But open to other format suggestions if makes implementation simpler

Requirements:
1. Leave `<sem-ver>` untouched and only hike the date and <increment> as needed if possible
2. Have an override to prevent this from happening for the purpose of official/stable releases
    A possible override is to detect the merge commit message to contain string "official release"
    An example of this can be found at [here](https://github.com/decentralized-identity/sidetree/blob/master/.github/workflows/unstable-release.yml#L11)

This task would be followed by another task that actually auto publishes the unstable packages to `npm`, but one step at a time!

**Comment by Cxxshyy** [comment]
im using chatGPT to try solve this

**Comment by Cxxshyy** [comment]
will raise a pr

**Comment by thehenrytsai** [comment]
Intent is realized by https://github.com/TBD54566975/dwn-sdk-js/pull/177.
