### ISSUE TITLE
Replace all hardcoded interface method string such as `CollectionsWrite` with `DwnMethodName` constants

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#138]
e.g.

'CollectionsWrite' --> DwnMethodName.CollectionsWrite
'CollectionsQuery' --> DwnMethodName.ProtocolsQuery

and so on.

**Comment by nearlyjuly** [comment]
Would that be something like:
```
export type ProtocolsConfigureDescriptor = {
  target: string;
  method: DwnMethodName.ProtocolsConfigure;
  dateCreated: number;
  protocol: string;
  definition: ProtocolDefinition;
};
```

(from interfaces/protocols/types.ts)

**Comment by thehenrytsai** [comment]
Yes, that's correct.

**Comment by nearlyjuly** [comment]
Have this so far https://github.com/TBD54566975/dwn-sdk-js/pull/153 is this sort of the right track?

**Comment by thehenrytsai** [comment]
Yes, except your PR has some errors currently.

**Comment by nearlyjuly** [comment]
Should this include PermissionsRequest too? It says on another issue that this will be undergoing a lot of changes soon.

**Comment by thehenrytsai** [comment]
#153 implemented this
