### ISSUE TITLE
Change `datePublished` descriptor property from epoch time to higher precision format

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#145]
Requirements:
1. Adopt ISO 8601 UTC format with microsecond precision enforcement, disallowing timezone selector (even 'Z'):
   `2022-10-14T10:20:30.405060` would be an accepted string.
   `2022-10-14T10:20:30.405060Z` would NOT be an accepted string.
   `2022-10-14T10:20:30.405` would NOT be an accepted string.

This allows us to compare time using a direct string compare.

See issue #113 and PR #142 for the same change on `dateCreated`.

**Comment by NikolaGundzikova** [comment]
Hi, can be this issue assigned to me?

**Comment by thehenrytsai** [comment]
Happy to!

**Comment by alexlemons** [comment]
Using the Performance API a precision string could potentially be generated using something like:

```js
function getCurrentDateInHighPrecision() {
	const now = (performance.timeOrigin + performance.now()).toFixed(3).split('.');
	return new Date(Number(now[0])).toISOString().replace('Z', now[1]);
}
```

However, Im not convinced that these values will be consistent and comparable when they're being generated in different environments/browsers, as there seems to be some variation in how the performance API is implemented.
Chrome currently has a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1365808) related to `performance.timeOrigin` which results in the date created being incorrect.

**Comment by alexlemons** [comment]
When ready the new Temporal API will include [Temporal.Instant](https://tc39.es/proposal-temporal/docs/instant.html) with nanosecond precision.

**Comment by thehenrytsai** [comment]
Change merged.
