### ISSUE TITLE
Add regex in JSON schema to check date properties in ISO 8601 UTC format 

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#147]
See date format requirements in #113.

The regex should be added for `dateCreated` and `datePublished` properties.

**Comment by rajakash-dev** [comment]
Can you please elaborate on how to use the regex , i have built and tested a regex exp but not sure how to use it in this use case.

**Comment by thehenrytsai** [comment]
You can see regex examples in https://github.com/TBD54566975/dwn-sdk-js/blob/ecd72c95e4ab31f68dbd74d36bc3502967d163da/json-schemas/definitions.json used for validations.

**Comment by rajakash-dev** [comment]
https://github.com/TBD54566975/dwn-sdk-js/pull/150

**Comment by duncanmak** [comment]
We can close this now!

**Comment by thehenrytsai** [comment]
Yes we can!
