### ISSUE TITLE
Generating JSDoc Documentation

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#171]
Generate SDK documentation based on the comment.

Most ideally, the doc generated should only include classes/functions in external exports found in [src/index.ts](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/index.ts)

**Comment by nearlyjuly** [comment]
I can have a go if no one else is working on it already. Is this about adding tags and descriptions to the indicated external exports?

**Comment by thehenrytsai** [comment]
@nearlyjuly, you are welcome to take on this for sure! This is about finding the desired tooling (perhaps JSDoc or TSDoc) and integrate it in this repo auto generate documentation as part of the CICD pipeline or build process.

Adding missing tags and/or descriptions is useful too, but less important for this item as the content of the documentation can improve over time.

**Comment by nearlyjuly** [comment]
Oh I see thanks, I have all next week off so I will see what I can do

**Comment by nearlyjuly** [comment]
I'm feeling biased towards TSDoc because Typedoc seems to tick all the boxes whether it's used locally or not. I will try and do a draft pr over the weekend/early next week.

**Comment by thehenrytsai** [comment]
Huge thanks to @nearlyjuly AND @pdxjohnny! This is now done thanks to you! 🥇 🚀 🎸
