### ISSUE TITLE
Add a RecordsCreate method to separate Writes out

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#185]

**Comment by csuwildcat** [comment]
We should probably consider this soon.

**Comment by csuwildcat** [comment]
Let's first decide if this is even the right path.

**Comment by thehenrytsai** [comment]
Proposal and discussion can be found at https://github.com/TBD54566975/technical-proposals/pull/2

**Comment by thehenrytsai** [comment]
No plan to undertake this task.
