### ISSUE TITLE
Finalize and implement data ingestion mechanism

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#198]
Currently data is ingested as base64url encoded property in the JSON message. This will not be acceptable if/when DWN is used to store large data.

A new proposal is to:
- [x] Remove support for multiple messages in one DWN request in favor of just one message per request
- [x] move the JSON metadata to an HTTP header
- [x] Add a new optional parameter `stream` to `processMessage(tenant, message, stream)`
- [x] Remove `encodedData` from being allowed in "write" messages
- [x] Return `encodedData` in message if it is under a certain size limit
- [x] Make `DataStore` a peer of `MessageStore`, another thin class/method `StorageController` that will manage the set/get of message and data
- [x] Change indexed key of data to tenant scoped [tenant + `messageCid` + (`commitId`, but this is more TODO for the future)]
- [x] Introduce `RecordsRead` message that will look something like:
```
{
  descriptor: {
    recordId: 'abc'
  }
}
```
- [x] Update the return type of `processMessage(...)` `MessageReply` to allow an optional stream so that `RecordsRead` can return data stream
- [x] Change the Node server code to 
   - Move the JSON metadata to an HTTP header
   - Leave the body for exclusive use to stream data

**Comment by andorsk** [comment]
@thehenrytsai totally agree with this. Great proposal. Related to "streaming", could eventually other streaming protocols ( like grpc ) be supportable? No rush or immediate need on this, but just want to know if it's possible down the road.

**Comment by mistermoe** [comment]
need to change API signature of `dwn.processMessage(message: any)` to `dwn.processMessage(message: any, data?: ReadableStream)`

[ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) looks to be supported across all major browsers and node. @shamilovtim is `ReadableStream` supported in react native?

**Comment by mistermoe** [comment]
@andorsk entirely possible _if_ we can figure out a transport agnostic serialization scheme. currently it is transport agnostic. the moment we end up using http headers or anything specific to http (aka multipart uploads) we'll sort of be tying ourselves to http and each individual transport will need to figure out how to support DWNs.

**Comment by andorsk** [comment]
@mistermoe thanks! I would be happy to help work on efforts to figure out a transport agnostic approach. I'm guessing there will be many implementors that will not want to bind their services to HTTP ( for various reasons ) and it would be great if we can not lock them out of DWN adoption cycles. 

Again, no real rush here, but would probably consider this a requirement for better adoption of DWN's, and so dismissing this req (imo) should be very thoughtfully done.

**Comment by shamilovtim** [comment]
react native uses https://github.com/github/fetch. i don't see anything specific about ReadableStream

**Comment by thehenrytsai** [comment]
@scrummitch and @andorsk, good call out. The complication on `RecordsQuery` is that multiple data content would be involved. Suggestions are welcome, but there is no "simple" solution currently. Two main paths were considered:

1. Having `RecordsQuery` return metadata and introduce `RecordsRead` to return one data content. This is the current preference
2. Multi-part` body`.

There was also discussion about allowing the encoded data if the data is small in size.

**Comment by simonwh** [comment]
Sounds like a solid proposal! 👍 

Regarding querying, it would be nice if we could avoid doubling the number of requests needed to return smaller data objects. Eg. chat messages, user preferences, "todo app items" and so on. Basically anything that is not larger files/blobs?

Maybe another alternative is to include a param to optionally return the data content in `RecordsQuery`? It would be up to the DWN impl. to fetch and return the data, or raise an error if the data size is too large -> explicit `RecordsRead` would be required, which could stream the response. It does complicate the interface a bit though...

**Comment by mistermoe** [comment]
totally agreed @simonwh . would hate to make a minimum of 2 requests to get a message AND it's data.

**Comment by andresuribe87** [comment]
My view is that it's important to eventually support multiple protocols. Consider the following examples:
* If I store media in my DWN (like a movie or music), then I want to be able to stream using [HLS](https://developer.apple.com/documentation/http_live_streaming).
* If I'm storing a large zip blob, then I want to be able to do a resumable transfer and do error recovery; so SFTP would make sense.
* If I'm storing sensor data from an IoT device, then MQTT (this assumes that DWNs will be _everywhere_).
* etc...

It would be nice to lay the foundation so that all of the above can be done. All the protocols described above are implemented at the Application layer, and typically use low level APIs provided by the operating system. So I **think** that we should stick to only ReadableStream objects instead of having a separate Files interface. Only my 2c though.

**Comment by thehenrytsai** [comment]
Hey folks, just sharing a rough plan of attack to support this issue, I might fork sub issues to tackle this in iterations:

- DONE - Remove support for multiple messages in one DWN request in favor of just one message per request
- Add a new optional parameter `stream` to `processMessage(tenant, message, stream)`, will need to sync up with @moe on his learning in browser environment
- Remove `encodedData` from being allowed in "write" messages
- Return `encodedData` in message if it is under a certain size limit
- If decided to have `MessageStore` being the "atomic operation" abstraction layer, then change the put method to take on `tenant` scope info, and the `stream` passed in:
  `put(tenant, message, indexes, stream): Promise<void>;`
- Else make `BlockStore` a peer of `MessageStore`, another thin class/method that will manage the set/get of message and data as atomic operations may be needed
- Change indexed key of data from "message CID" to tenant scoped [tenant + `recordId` + (`commitId`, but this is more TODO for the future)]
- Introduce `RecordsRead` message that will look something like:
```
{
  descriptor: {
    recordId: 'abc'
  }
}
```
- Change the return type of `processMessage(...)` from `MessageReply` to a stream so that `RecordsRead` returned binary can be supported, else need to think of alternatives
- Change the Node server code to 
   - Move the JSON metadata to an HTTP header
   - Leave the body for exclusive use to stream data

**Comment by nearlyjuly** [comment]
In https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/records/messages/records-write.ts there are two versions of "isInitialWrite" at lines 338 and 346, is that how it should be?

**Comment by thehenrytsai** [comment]
@nearlyjuly, yes, one is an instance method and the other is static method.

**Comment by thehenrytsai** [comment]
This is now complete
