### ISSUE TITLE
Support range query on `dateCreated`

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#214]
While thinking about how to add range query support on `dateCreated` to `MessageStore`, the following question came up:

What is the right level of **query abstraction** for `MessageStore`? To be clear, this is not something a normal SDK user will ever see, it's more for maintainability and writers of new `MessageStore` adaptors. I see the following abstraction choices:

  1. Completely DWN specific and query message aware
     eg. `query(RecordsQuery|ProtocolsQuery|etc)`
     - pros
       - Thinner business/handler layer because the `MessageStore` will end up doing a lot of the heavy lifting
     - cons
       - unnecessary DWN specific knowledge that all `MessageStore` implementors will have to be aware of, which results in duplication of the same DWN logic across all adaptors.

     Not a good choice overall

  2. Tailored for DWN use case but no direct knowledge of DWN or query message type (`RecordsQuery`, `ProtocolsQuery`, etc)
     eg. `query(exactAndMatches, rangeAndMatches)`
     - pros
       - clear expectation/interface for the adaptor writer thus arguably easiest to implement against
       - user-facing SDK layer and the message store layer can share the same data model thus also easiest for us to implement this feature
      - cons
        - may need to add or change method arguments if/when we need to expand query capabilities (case in point, range query)
       
  3. Generic well-known query language with no knowledge of DWN at all
     eg. `query(subsetOfMongoQuery)`
     - pros
       - known/familiar syntax for all capabilities we will ever need (to be clear though, SDK user will not see/use this)
     - cons
       - self-imposed complexity - need to translate SDK layer data model into the chosen language (such as Mongo query language syntax)
       - adaptor developers will probably need to parse and convert the generic query into objects they can reason about for their choice of DB, which option 2 essentially provides
       - still need to specify precisely the subset of the full query language to be implemented by adaptor implementor

I am leaning towards option 2 right now, but thoughts welcome!

**Comment by andresuribe87** [comment]
Would you consider removing the interface all together :) ?

I argue that defining the abstraction now is premature, and I propose waiting until there is strong interest in having multiple backing stores yet. Of course, I might just be uninformed and that need may already exist =)


As a separate point, should `query` return a stream of data, instead of a full array with all the things that matched?

**Comment by thehenrytsai** [comment]
@andresuribe87, thanks for the thoughts, always glad someone else is able to provide input to these issues.

> that need may already exist

Yes, the need already exists, TBD internally and externally a few community member are already looking at writing their own adaptors.

> query return a stream of data

Yes, there is a separate issue #198 on revamping how data is getting in and out.
