### ISSUE TITLE
Don't use file extensions when importing JS/TS

### ISSUE THREAD

**Issue by shamilovtim** [TBD54566975/dwn-sdk-js#222]
When importing: `import { Foo } from './Bar.js`. Don't include .js or .ts. I've found that this can cause problems with bundlers.

**Comment by thehenrytsai** [comment]
Thanks @shamilovtim for filing the issue and would like to understand more what bundler are you referring to and what trouble did you run into.

My knowledge of bundlers is extremely limited, but I was under the impression that imports with .js extension is preferred and even expected by many bundlers:

1. webpack - .js extension is the simplest way, module will be included with no additional resolution - https://webpack.js.org/concepts/module-resolution/#module-paths
1. rollup - seems to expect it - https://rollupjs.org/es-module-syntax/
1. esbuild - the one we use - seems to bundle fine

The hope is of course the SDK consumer never has to worry about bundlers, is our esbuild bundle causing you trouble?

**Comment by mistermoe** [comment]
@shamilovtim we use `tsc` to transpile to js and then `esbuild` to bundle. @thehenrytsai if we use `esbuild` to transpile + bundle we won't have to use extensions anymore

**Comment by thehenrytsai** [comment]
@shamilovtim, is this still a blocker?

**Comment by shamilovtim** [comment]
Conclusion: Node community is moving toward requiring the file extensions so while they're weird and will confound contributors, we have to deal with them.

**Comment by thehenrytsai** [comment]
Reference: https://nodejs.org/api/esm.html#mandatory-file-extensions
