### ISSUE TITLE
Use import type for all type imports and add lint rule with error to enforce it

### ISSUE THREAD

**Issue by shamilovtim** [TBD54566975/dwn-sdk-js#223]
When importing types we should always use `import type`. Without using `import type` for typedefs we risk bundling unnecessary code, especially with bundlers like Metro that don't support tree shaking.

- [x] Add lint rule for import type with error for violations
- [x] Fix all instances where types aren't imported with `import type`

**Comment by wavesrcool** [comment]
Hello! I created a node cli script to use RegEx groupings to identify:

1.) all of the exported types in src/
2.) all import instances of those types not currently using ```import type```

I have included below the log file of all exported types in src/ in the event it may be helpful for reference. This is my first ever pull request draft so apologies upfront for any obvious oversights!

- file: src/core/types.ts
- matches: 
		- BaseMessage,
		- BaseDecodedAuthorizationPayload,
		- Descriptor,
		- TimestampedMessage,
		- DataReferencingMessage

- file: src/did/did-resolver.ts
- matches: 
		- DidDocument,
		- DwnServiceEndpoint,
		- ServiceEndpoint,
		- VerificationMethod,
		- DidResolutionResult,
		- DidResolutionMetadata,
		- DidDocumentMetadata

- file: src/dwn.ts
- matches: 
		- DwnConfig

- file: src/interfaces/hooks/messages/hooks-write.ts
- matches: 
		- HooksWriteOptions

- file: src/interfaces/hooks/types.ts
- matches: 
		- HooksWriteDescriptor,
		- HooksWriteMessage

- file: src/interfaces/permissions/types.ts
- matches: 
		- PermissionScope,
		- PermissionConditions,
		- PermissionsRequestDescriptor,
		- PermissionsRequestMessage,
		- PermissionsGrantDescriptor,
		- PermissionsGrantMessage

- file: src/interfaces/protocols/messages/protocols-configure.ts
- matches: 
		- ProtocolsConfigureOptions

- file: src/interfaces/protocols/messages/protocols-query.ts
- matches: 
		- ProtocolsQueryOptions

- file: src/interfaces/protocols/types.ts
- matches: 
		- ProtocolsConfigureDescriptor,
		- ProtocolDefinition,
		- ProtocolRuleSet,
		- ProtocolsConfigureMessage,
		- ProtocolsQueryDescriptor,
		- ProtocolsQueryMessage

- file: src/interfaces/records/messages/records-delete.ts
- matches: 
		- RecordsDeleteOptions

- file: src/interfaces/records/messages/records-query.ts
- matches: 
		- RecordsQueryOptions

- file: src/interfaces/records/messages/records-write.ts
- matches: 
		- RecordsWriteOptions,
		- CreateFromOptions

- file: src/interfaces/records/types.ts
- matches: 
		- RecordsWriteDescriptor,
		- RecordsWriteMessage,
		- UnsignedRecordsWriteMessage,
		- RecordsQueryDescriptor,
		- RecordsQueryFilter,
		- RangeCriterion,
		- RecordsWriteAttestationPayload,
		- RecordsWriteAuthorizationPayload,
		- RecordsQueryMessage,
		- RecordsDeleteMessage,
		- RecordsDeleteDescriptor

- file: src/interfaces/types.ts
- matches: 
		- MethodHandler

- file: src/jose/jws/general/types.ts
- matches: 
		- GeneralJws,
		- SignatureEntry,
		- JwsHeaderParameters,
		- SignatureInput

- file: src/jose/types.ts
- matches: 
		- KeyMaterial,
		- Jwk,
		- PublicJwk,
		- PrivateJwk

**Comment by thehenrytsai** [comment]
This is now done.
