### ISSUE TITLE
Release 0.0.22 contains a type error on blockstore-level.d.ts

### ISSUE THREAD

**Issue by sondreb** [TBD54566975/dwn-sdk-js#237]
The current released package doesn't work without manual editing the type definition for blockstore-level.d.ts.

It was fixed in the commit right after the latest release, so this will be fixed on next release, but consider releasing it soon so the package works again:

![image](https://user-images.githubusercontent.com/309938/221850207-28b4e36c-f89c-4272-ae8a-d05465c23ffd.png)

**Comment by thehenrytsai** [comment]
I just released [v0.0.23](https://www.npmjs.com/package/@tbd54566975/dwn-sdk-js/v/0.0.23), hopefully that addresses the issue!

**Comment by sondreb** [comment]
Thanks, fixed this issue!
