### ISSUE TITLE
Release 0.0.23 contains an import that makes generated code require use of Node.js (CommonJS) imports

### ISSUE THREAD

**Issue by sondreb** [TBD54566975/dwn-sdk-js#238]
It appears the latest release have an import in the `cid.ts` file that makes the TypeScript compiler include this in the top of the source output:

```
/// <reference types="node" resolution-mode="require"/>
```

This is caused by this import in the `cid.ts` file:

```import { Readable } from 'stream';```

This "Readable" is only used as a type-definition for the `computeDagPbCidFromStream` method.

**Comment by thehenrytsai** [comment]
@sondreb feel free to file new issue. Closing as fixed.
