### ISSUE TITLE
Update IPFS related dependencies to latest version

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#245]
Latest state of this issue:

✅ "@ipld/dag-cbor": "9.0.0",
✅ "interface-blockstore": "4.0.1"
✅ "ipfs-unixfs": "11.0.0",
✅ "ipfs-unixfs-exporter": "13.1.0",
✅ "ipfs-unixfs-importer": "14.0.1",
✅ "multiformats": "11.0.2",

Some dependencies are not backwards compatible thus will break build/compilation so will require update to code.

More annoying is that it appears some of the latest IPFS packages aren't exporting types correctly/fully which may require changes to IPFS repos. For reference, following errors are thrown when attempting to compile:

```
node_modules/@ipld/dag-pb/dist/src/index.d.ts:22:29 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

22 export type PBLink = import('./interface').PBLink;
                               ~~~~~~~~~~~~~

node_modules/@ipld/dag-pb/dist/src/index.d.ts:23:29 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

23 export type PBNode = import('./interface').PBNode;
                               ~~~~~~~~~~~~~

node_modules/@ipld/dag-pb/dist/src/util.d.ts:15:61 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

15 export function createNode(data: Uint8Array, links?: import("./interface").PBLink[] | undefined): PBNode;
                                                               ~~~~~~~~~~~~~

node_modules/@ipld/dag-pb/dist/src/util.d.ts:23:29 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

23 export type PBLink = import('./interface').PBLink;
                               ~~~~~~~~~~~~~

node_modules/@ipld/dag-pb/dist/src/util.d.ts:24:29 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

24 export type PBNode = import('./interface').PBNode;

```

**Comment by nearlyjuly** [comment]
Is it worth hanging on until this documentation https://github.com/microsoft/TypeScript/issues/52593 is ready?

**Comment by thehenrytsai** [comment]
@nearlyjuly now sure how it is related exactly? I have begin by updating the `ipfs-unixfs-importer` dependency: #248.

**Comment by nearlyjuly** [comment]
Probably not worth it on second thoughts, was an initial reaction as I can see multiformats stopped supporting cjs since version 10, and issues such as 222 and 223 point to maybe having a strategy when this happens again for other dependencies. But I guess people will speak up and fix as and when needed.

**Comment by shamilovtim** [comment]
Could you make these permissive toward minor versions (`^ symbol`) so that there isn't separate resolution with other packages like ion-tools @thehenrytsai @diehuxx ?

Thank you!

**Comment by shamilovtim** [comment]
Related: https://github.com/decentralized-identity/ion-tools/issues/53

**Comment by thehenrytsai** [comment]
Closing this issue with a targeted issue for action #385.
