### ISSUE TITLE
add stricter TypeScript check in tsconfig.json

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#261]
Add `"strict": true"` to `tsconfig.json/tsconfig.cjs.json` with `"strictNullChecks": true` being the fallback option if `"strict": true"` is too painful to enforce.

This will allow projects having stricter TS config rules to use the library without hitting errors.

**Comment by duncanmak** [comment]
Hello @thehenrytsai and @diehuxx, thanks for merging in my PRs.

Do you think this issue should be closed now? And keep any follow-ups in #298?

**Comment by thehenrytsai** [comment]
@duncanmak , was contemplating if we should wait until the "FIXME" are fixed. But I'll  close and open a separate issue for those too.
