### ISSUE TITLE
consider changing `StorageController` to a class that is instantiated with all of the stores

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dwn-sdk-js#288]
I see that all interface methods, in their constructors, take `messageStore`, `dataStore`, and now `eventLog`. e.g.
* [records-delete](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/records/handlers/records-delete.ts#L15)
* [records-write](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/records/handlers/records-write.ts#L16)
* [records-query](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/records/handlers/records-query.ts#L16)
* [records-read](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/records/handlers/records-read.ts#L15)

but it seems like they're almost always passed to [StorageController](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/store/storage-controller.ts)  to do stuff like queries, puts etc. i do see some areas that use _just_ `messageStore.query` and not `StorageController.query`, presumably because `StorageController` also returns the respective data if its under a certain size?

it seems like, we could instantiate a `StorageController` instance in `dwn.create` and pass that to each individual handler. `StorageController` could simply have getters for `messageStore` when its needed individually. 

curious to hear ppls thoughts here. basically, since we have `StorageController` now, we might as well leverage it to reduce the # of arguments that are passed to each interface method handler

**Comment by duncanmak** [comment]
I started working on this here: https://github.com/TBD54566975/dwn-sdk-js/pull/338

I just re-read @mistermoe's message above, I think the tests are failing in my PR because I've confused 'messageStore.query` with `storageController.query`, even though their argument lists are compatible.

**Comment by thehenrytsai** [comment]
`StorageController` is refactored and is on "less" critical path than before, for instance, `put()` is no longer going through `StorageController`. The debate in PR #338 also seems to suggest that it is not all bad that dependencies are injected explicitly, so closing this and we can reopen again if the code is become too unwieldy that requires a second look.
