### ISSUE TITLE
JSDoc for Web5 JS SDK and generated API Documentation

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/dwn-sdk-js#303]
For handoff to @dayhaysoos so we can put https://developer.tbd.website/docs/api/

**Comment by ALRubinger** [comment]
I put it in the wrong repo, apologies Henry! Yes absolutely let’s handle in
web5-js — thank you!!

**Comment by thehenrytsai** [comment]
@ALRubinger, no worries at all! Closing!

**Comment by ALRubinger** [comment]
@thehenrytsai - Yo, @mistermoe and I aren't seeing the `web5-js` issue; are we missing something? If it's not there, should we xfer this one? Thank you!!

**Comment by ALRubinger** [comment]
Updating for the record only; the correct issue for this, in the correct repo, is: https://github.com/TBD54566975/web5-js/issues/34

This issue is closed as invalid; in the wrong place :P
