### ISSUE TITLE
Delete descendant records upon parent record deletion

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/dwn-sdk-js#311]
Moving discussion from this thread: https://github.com/TBD54566975/dwn-sdk-js/pull/307#discussion_r1166350813

## Context
Records within a protocol exist in a hierarchy. Determining what actions a DID can perform on a given record in protocol space involves traversing a chain of ancestors. When a record in the hierarchy is deleted, what should we do to its descendants?

## Approaches
1. 💀 **Delete all descendants:** This is the simplest to implement and reason about. However it may be too restrictive.
2. 🪦 **Retain descendants:** This is possible because deletes are implemented as tombstones. In this case, the deleted record will no longer appear in `RecordsReads` or `RecordsQuery` response, but its descendants may. But how do we handle writing/updating new child records? Much nuance.
3. 🧘‍♀️ **Enlightened Centrism**: Allow developers both options. Consider two actions called `delete` and `delete-descendants`. The former deletes only the single record, whereas the latter deletes all descendants.

**Comment by csuwildcat** [comment]
Let's go with option 3

**Comment by thehenrytsai** [comment]
This is now implemented as `prune`.
