### ISSUE TITLE
Create GH issues for each TODO in codebase and link the corresponding issue number (eg. #123)

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dwn-sdk-js#32]
For each `// TODO:` in codebase:
- create respective GH issue
- reference issue # next to each TODO in codebase

**Comment by 0xzoz** [comment]
I have taken care of all `TODOS:` in  both `message.ts` and `/store/message-store-level.ts`

**Comment by bnonni** [comment]
Happy to help with this too. I don't see issues already created for TODOs in the following files:
- [did-resolver.ts](https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/did/did-resolver.ts)
- [permissions-request.ts](https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/interfaces/permissions/handlers/permissions-request.ts)
- [verifier.ts](https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/jose/jws/general/verifier.ts)
- [message-store.ts](https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/store/message-store.ts)

Will link to issues in codebase and submit PR from fork. 
Please lmk if I missed something and accidentally created a duplicate issue.

**Comment by thehenrytsai** [comment]
This is done.
