### ISSUE TITLE
Revisit protocol definition schema style and consider adopting a style with predefined property names

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#326]
At minimum we should change `allow` into an array so that the same actor/role with different paths can be defined:

e.g. (just for consideration)
```json
"allow": [{
    "actor/role": "author",
    "of": "album",
    "to": ["create", "read"]
  },
  {
    "actor/role": "anyone",
    "to": ["read"]
  },
  {
    "actor/role": "author",
    "of": "photo",
    "to": ["update", "delete"]
  }
]
```

Also consider using this opportunity to reexamine choice of property names throughout the entire schema. Perhaps to `of` -> `protocolPath`, `to` -> `action/operation`, `labels` -> `constraints`,

**Comment by diehuxx** [comment]
I figure we should rip this off like a bandaid, and I'm in favor of having all property names be predefined. I personally don't find the current declarative style more readable, and it leads to restrictions that I find hard to reason about.

Here's my proposal:
1. Rename certain fields
  a. `of` -> `protocolPath`
  b. `to` -> `action`
  c. `records` at the top level of the definition -> `recordsHierarchy` or just `hierarchy`
  d. `records` nested -> `descendants`
  e. `labels` -> `recordTypes`
2. Make all property names predefined
  a. Turn `labels` into an object array named `recordTypes`. Use `labels` as a property within each of the contained objects.
  b. Turn `recordsHierarchy` into an array of `ProtocolRuleSets`. Use `labels` as a property name within each `ProtocolRuleSet`


Here's Typescript types illustrating the above:

```typescript
type ProtocolDefinition = {
  recordTypes: ProtocolRecordType[],
  recordHierarchy: ProtocolRuleSet[],
};

type ProtocolRecordType = {
  label: string,
  schema?: string,
  dataFormats?: string[]
};

type ProtocolRuleSet = {
  label: string,
  allow?: {
    actor: ProtocolActor,
    protocolPath: string,
    actions: ProtocolAction[]
  },
  descendants?: ProtocolRuleSet[],
};

enum ProtocolActor {
  ANYONE = 'anyone',
  AUTHOR = 'author',
  RECIPIENT = 'recipient',
};

enum ProtocolAction {
  READ = 'read',
  WRITE = 'write',
}
```

And a short example protocol
```json
{
  "recordTypes": [
    {
      "label": "image",
      "schema": "http://example.com/image",
      "dataFormats": ["image/jpeg"]
    },
    {
      "label": "response",
      "schema": "http://example.com/response",
    }
  ],
  "recordHierarchy": [
    {
      "label": "image",
      "allow": [
        {
          "actor": "anyone",
          "actions": ["write"]
        },
        {
          "actor": "author",
          "protocolPath": "image",
          "actions": ["read"]
        }
      ],
      "descendants": [
        {
          "label": "response",
          "allow": [
            {
              "actor": "recipient",
              "protocolPath": "image",
              "action": ["read", "write"]
            }
          ],
        }
      ]
    }
  ]
}
```

**Comment by thehenrytsai** [comment]
@diehuxx, supportive to all! In addition:

1. Would prefer `"label": "image"` under `recordHierarchy` be `"recordType": "image"`
1. `alias`, `name`, `friendlyName`, or even `id` may be good substitutes for `label` under `recordTypes` as they arguably show the intent better.

**Comment by csuwildcat** [comment]
Maybe `path` instead of `protocolPath`?

**Comment by thehenrytsai** [comment]
This is now completed.
