### ISSUE TITLE
Validate protocol definition upon ingestion

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/dwn-sdk-js#332]
Currently we don't do any validation of a protocol definition within `ProtocolsConfigure` before we store the definition. There are a few things we can check to validate that the protocol definition isn't broken before we try to write records to it.

1. Validate that the `protocolPath` in a given rule set is not longer than the ancestor path to reach that rule set. Currently we check this upon `Records*` handling [here](https://github.com/TBD54566975/dwn-sdk-js/blob/a2d1d0381b9b7fc7284ba89fc0904e3cfac6a7f1/src/core/protocol-authorization.ts#L392-L395)
2. As we refactor towards #326, we will need to validate that
  a. no two `recordTypes` have the same `id`
  b. no two `descendants` in a given ruleset have the same `recordType`

**Comment by thehenrytsai** [comment]
@diehuxx, just sanity check so I understanding the issue fully: I am pretty sure we do validation of the protocol definition within `ProtocolsConfigure` during `parse()` before we store the definition as well as during `create()`. You were modifying the schema for it, so I don't fully understand, can you clarify?

Agree that we can and should do more validation beyond basic JSON Schema, especially if we revamp the protocol definition schema, but this is true in general to all DWN message types.

**Comment by diehuxx** [comment]
> Agree that we can and should do more validation beyond basic JSON Schema, especially if we revamp the protocol definition schema, but this is true in general to all DWN message types.


Yep this is what I meant. Sorry, should have been more clear in the  description! We definitely do JSON schema validation, which covers a lot of what we need. But there's a few more validations (like those listed in the description) that we need to add to the code, or I need to figure out how to do those checks within JSON schema.

**Comment by thehenrytsai** [comment]
We have revamped the protocol definition its code quite drastically, this is no longer relavant.
