### ISSUE TITLE
instrument telemetry into codebase

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dwn-sdk-js#36]
- document reasons for why having telemetry in dwn would be beneficial
- choose lib we want to use for telemetry
- instrument codebase with said lib. Consider using [open telemetry](https://opentelemetry.io/)

**Comment by ALRubinger** [comment]
Community has some discussion about data collection you may wanna speak to :)

https://discord.com/channels/937858703112155166/937858703820980296/991853617931894876

**Comment by thehenrytsai** [comment]
Aggressively closing because:

1. Community members have express the distaste for it
2. This is not something we will get to in the near/mid term

We can open/reopen when the time comes.
