### ISSUE TITLE
Move blockstore tests out of `handlers/records-write.spec.ts`

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/dwn-sdk-js#362]
[Context](https://github.com/TBD54566975/dwn-sdk-js/pull/360#discussion_r1192623618)

There are a few tests in `handlers/records-write.spec.ts` that have nothing to do with testing deleting records but instead test `block-store-level.ts`. We should either move these to `blockstore-level.spec.ts`, `data-store-level.spec.ts`, or maybe just remove them if we're already testing that functionality in other tests.

**Comment by thehenrytsai** [comment]
I believe this is done in https://github.com/TBD54566975/dwn-sdk-js/commit/03bcb1ca49fd8cf95be76db0f7ae19090598cca4
