### ISSUE TITLE
Remove the requirement that a protocol URI must be passed as a filter to protocols.query()

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#375]
### Background:
Currently a protocol URI must be passed as a filter to `protocols.query()`

### Objective:
- The protocol URI prop should be optional, and if omitted, should return all installed protocols.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by KshitijBharde** [comment]
Hi @thehenrytsai, I would like to work on this issue.

**Comment by Rizina** [comment]
picking this up

**Comment by EbonyLouis** [comment]
@KshitijBharde Hey, do you still want to work on this issue?

**Comment by thehenrytsai** [comment]
This is done.
