### ISSUE TITLE
Add recursive record support

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#379]

**Comment by thehenrytsai** [comment]
Thanks @diehuxx for putting the requirements together!

A few comments/questions:
1. > this is useful because we may want to terminate a recursive list of records with a record of the same schema and dataFormat but with different $actions rule

   Agree that there is no ambiguity but can this really terminate the list? Can't one just write another chat message as usual and attach to the parent of the "terminating" chat message?
   
 2. If I understand this correctly, it means that we are allowing a very very very long "chain" to be constructed and ever growing. This would render this feature not usable very quickly with current implementation because of we construct the ancestor chain all the way back to the root. Since we now have `protocolPath`, we can (and must) try avoiding walking back to the root all altogether (ie. nuke `constructAncestorMessageChain()`) and just take advantage of `protocolPath` in order for this feature to be useable.
 
 3. The ship has sailed on this one it seems: but what **problem/scenario** does this feature solve/enable?

    I understand with this, one can form a very deep tree with very minimal syntax, but why is this needed/useful?

**Comment by diehuxx** [comment]
>    Agree that there is no ambiguity but can this really terminate the list? Can't one just write another chat message as usual and attach to the parent of the "terminating" chat message?


You're right that someone can just continue the conversation in another branch. This is admittedly a contrived example, just meant to illustrate the edge cases. 


>  2. If I understand this correctly, it means that we are allowing a very very very long "chain" to be constructed and ever growing. This would render this feature not usable very quickly with current implementation because of we construct the ancestor chain all the way back to the root. Since we now have `protocolPath`, we can (and must) try avoiding walking back to the root all altogether (ie. nuke `constructAncestorMessageChain()`) and just take advantage of `protocolPath` in order for this feature to be useable.


Very good point, I'll need to think through implementation and update #389. I'll follow up on this point later today or tomorrow.


>  3. The ship has sailed on this one it seems: but what **problem/scenario** does this feature solve/enable?
> 
> 
> 
>     I understand with this, one can form a very deep tree with very minimal syntax, but why is this needed/useful?

Gonna sauce this one to @csuwildcat.

**Comment by csuwildcat** [comment]
There's no non-comical way to do messages as a descending thread for all the many app types that require it without a recursive rule. We definitely need something better than unchained timestamps, and this recursive proposal does it, so for that reason, it's a good idea.

**Comment by thehenrytsai** [comment]
@csuwildcat, why is this proposal less comical? Yes, a chat message can point to another chat message as its parent with this proposal, but A chat message can already do so **without** this proposal by declaring the logical parent in its data, so what is the problem that this proposal alone solves? 

A difference I can see with this proposal is that one can potentially walk the ancestor chain **one parent at a time** to hit-test if it is a descending message of certain ancestor, but that's a pretty comical thing to do no? So surely this is not the intent.

Just trying to get to the intent succinctly (and it is still not succinct), else we might just be introducing complexity for little gain.

Adding @mistermoe and @frankhinek in case they have a slam dunk answer that's more convincing to me, @diehuxx feel free to take a shot at answering too!

**Comment by csuwildcat** [comment]
We can't parse and efficiently deliver queries if the linkages are in the encrypted app data portion.

**Comment by thehenrytsai** [comment]
@csuwildcat, got it, so if I am interpreting correctly: this proposal alone does not solve any problems by itself. but, it sets the foundation for future proposals for querying against the tree structure of protocol messages, which would be the first precedence for a query based on a property that does not exist in the message itself (ie. `descendantsOf`?).

Such proposal sounds pretty cool but also sounds even more complex than this proposal... and still, what is an actual scenario that can't be achieved without the `descendantsOf`? Using the chat app example, the concept of a 'sub-thread' can be modeled using a `sub-thread` record type under the `main-thread` type. This allows developers to query all messages under any sub-thread without requiring additional features.

From a technical stand point, implementing performant tree traversal over relational DB or mongoDB is non-trivial in my book, especially when the proposed use case easily involve tree depths of hundreds or even thousands. Not to mention we'd need to hand-roll implementation in a key-value store called LevelDB... In principle, I would encourage keeping the app data model as flat as possible as the recommendation to web5 apps unless there is no other option.

If the goal is to provide developers with query capabilities to support their application use cases, an alternative approach that would probably offer bigger bang-for-the-buck with minimal complexity (which was proposed last year) is to provide an indexed "metadata" property. This would allow developers to populate and modify it with any desired value. This can support the sub-thread scenario mentioned and beyond.

Again sorry for coming across as uncooperative, I genuinely want to be supportive of all proposals!!! But I also need to fully comprehend them before endorsing them!

**Comment by csuwildcat** [comment]
How do I reply/quote to a given message in a thread such that even if 100 more messages were sent between them over 2 days the two could be directly associated without decrypting their data?

**Comment by thehenrytsai** [comment]
1. `sub-thread` record type; and/or
1. indexed "metadata" property

Both described above.

**Comment by csuwildcat** [comment]
@thehenrytsai I'm going to try modeling the sub-thread idea with a few other use cases to think through if that suffices.

**Comment by thehenrytsai** [comment]
Closing as we won't be tackling this anytime soon if ever. Can resurrect this issue if the time comes.
