### ISSUE TITLE
Replace all `new Error(...)` with `new DwnError(...)`

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#387]
### Background:
currently we have `new DwnError(...)` and `new Error(...)` throughout the code

### Objective:
- Replace all `new Error(...)` with `new DwnError(...)`
- List of DwnError codes can be found here: `src/core/dwn-error.ts`

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by tux7P** [comment]
picking this up🙂

**Comment by EbonyLouis** [comment]
@tux7P Yay! I'll assign it to you now.

I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **However, feel free to start working on it, but I'd recommend holding off on submitting your PR until the event begins.** 

> to be eligible for Hacktoberfest's official prizes make sure you're registered, registration [is now open.](https://hacktoberfest.com/auth/) Reach out if you need any help 🥳

**Comment by FroostyCodes** [comment]
Hi @EbonyLouis @thehenrytsai 
If this is not being worked on, I would like to work on it.

**Comment by EbonyLouis** [comment]
@tux7P Hey do you still want to work on this issue?

**Comment by EbonyLouis** [comment]
@FroostyCodes it's all yours, assigning it to you now, thanks! 🥳

**Comment by Tushar98644** [comment]
@EbonyLouis can i work on this if the current assignee is inactive ? Thanks

**Comment by flothjl** [comment]
@Tushar98644  are you still wanting to work on this? if not, I can pick it up.
@EbonyLouis

**Comment by EbonyLouis** [comment]
@flothjl thanks, you can work on this
