### ISSUE TITLE
Consider supporting both compressed and uncompressed SECP256K1 public key

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#397]
### Background:

Currently, our SDK libraries assume uncompressed SECP256K1 keys.

Compressed key is now the new default for `@noble/secp256k1` v2, instead of uncompressed keys.

### Task Details:
- [ ] Consider supporting both compressed and uncompressed SECP256K1 public key in input of method eciesSecp256k1Encrypt().
- [ ] Convert key creation method(s) to produce compressed key instead uncompressed key.

A good place to start is https://github.com/TBD54566975/dwn-sdk-js/blob/660bc91b916f3b4d4b4a9daf16851bc7675cbd30/src/utils/encryption.ts#L70

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by hkwi** [comment]
picking this up

**Comment by hkwi** [comment]
It looks that eciesSecp256k1Encrypt() does already accepts both compressed and uncompressed, because internal eciesjs.encrypt() accespts both.

```
const { PrivateKey, encrypt, decrypt} = await import("eciesjs");
const sk = new PrivateKey();
const data = Buffer.from("Hello world");
console.log(decrypt(sk.secret, encrypt(sk.publicKey.uncompressed, data)).toString());
// Hello world
console.log(decrypt(sk.secret, encrypt(sk.publicKey.compressed, data)).toString());
// Hello world
```

So, I think `uncompressedPublicKey` can be just renamed to `publicKeyBytes`.

**Comment by thehenrytsai** [comment]
> looks that eciesSecp256k1Encrypt() does already accepts both compressed

That's good news, probably just double check if there are tests or add tests to make sure both compressed and uncompressed key paths work.

Also just did a quick search on `uncompressed` and found that there is also `publicJwkToBytes()` that can be switched to output compressed key instead.

**Comment by blackgirlbytes** [comment]
Hey there, @hkwi! I'm just checking to see if you're still working on this issue!

**Comment by hkwi** [comment]
Thank you for ping, sorry for delay, I created a PR.
