### ISSUE TITLE
Build helpful errors object using returned errors

### ISSUE THREAD

**Issue by 0xzoz** [TBD54566975/dwn-sdk-js#45]
- Every time a validation function is called the errors property is overwritten.
eg const errors = [...validateFn.errors];

https://github.com/TBD54566975/dwn-sdk-js/blob/98202beeed579628203b45fdaad45583409bd743/src/message.ts#L50-L56

**Comment by thehenrytsai** [comment]
Taken the approach or returning the immediate error.
