### ISSUE TITLE
Add flag to only keep one record under a given path

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#455]
Imagine a use case like 'bio' as a protocol path, where you only want to allow one bio object. The desire is to be able to add some $flag property that tells the DWN to only ever keep 1 record and the latest version of that record to come in under a path. The other ask is to make RecordsRead support not requiring a `recordId` and reading back the first record under a filter, if the `recordId` is not provided.

**Comment by thehenrytsai** [comment]
I think this is a dup of #467, keeping that one since it has more context and input, closing this one.
