### ISSUE TITLE
IndexLevel filter not working correctly

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/dwn-sdk-js#458]
I've been porting over the IndexLevel code to React Native, and ran into a bug with the range filters used by the `IndexLevel` class. 

An iterator is used to find what values are "less than" or "greater than" the target value. This breaks down, because the LevelDB database sorts these keys in byte order.

Here's an example of a failing test (`index-level.spec.ts`)
```
it('supports range queries with variable digit count', async () => {
  await index.put('1', { digit: 1 });
  await index.put('2', { digit: 2 });
  await index.put('10', { digit: 10 });

  const resp = await index.query({
    digit: {
      gte: '10'
    }
  });

  expect(resp.length).to.equal(1);
});
```

Instead of just one record being returned, we instead see that all three records are returned to the user. This is because the byte order of these keys are actually: `[10, 1, 2]`

---

This bug can also be seen with the `EqualFilter` as well with the following test:
```
it('supports equality queries', async () => {
  await index.put('1', { digit: 1 });
  await index.put('2', { digit: 2 });
  await index.put('10', { digit: 10 });

  const resp = await index.query({
    digit: 1
  });

  expect(resp.length).to.equal(1);
});
```

In this test, both the `"1"` and `"10"` records are returned, even though only one of those actually has a digit equal to 1.

**Comment by thehenrytsai** [comment]
Closing, thanks @amika-sq!
