### ISSUE TITLE
Replace publicKeyJwk validation with JSON Schema based validation

### ISSUE THREAD

**Issue by 0xzoz** [TBD54566975/dwn-sdk-js#46]
Replace publicKeyJwk validation with JSON Schema-based validation
  
- more info about the `publicKeyJwk` property can be found here:
- https://www.w3.org/TR/did-spec-registries/#publickeyjwk

https://github.com/TBD54566975/dwn-sdk-js/blob/98202beeed579628203b45fdaad45583409bd743/src/message.ts#L146-L151

**Comment by thehenrytsai** [comment]
Dupe of #68, which is referenced by code.
