### ISSUE TITLE
Check controller and DID in kid are the same

### ISSUE THREAD

**Issue by 0xzoz** [TBD54566975/dwn-sdk-js#47]
Figure out if we need to check to ensure that `controller` === did in kid are the same. This may matter more for a `PermissionsRequest`

https://github.com/TBD54566975/dwn-sdk-js/blob/98202beeed579628203b45fdaad45583409bd743/src/message.ts#L150-L154

**Comment by thehenrytsai** [comment]
Duped of #67, which is referenced by code.
