### ISSUE TITLE
Workaround for search-indexlib not importing type 

### ISSUE THREAD

**Issue by 0xzoz** [TBD54566975/dwn-sdk-js#48]
Find a workaround for search-indexlib not importing type `SearchIndex`

https://github.com/TBD54566975/dwn-sdk-js/blob/98202beeed579628203b45fdaad45583409bd743/src/store/message-store-level.ts#L18-L24

**Comment by thehenrytsai** [comment]
https://github.com/TBD54566975/dwn-sdk-js/pull/54 is tracking to fix this.

**Comment by thehenrytsai** [comment]
Fixed.
