### ISSUE TITLE
Investigate and choose new timer for DWN store open and close

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/dwn-sdk-js#483]
**Update: This has been partially addressed by #501, which fixed `LevelWrapper#open`. It is a good first issue to fix `LevelWrapper#closed` by following the same pattern as #501.**

While trying to track down a performance issue with the Web5 JS SDK, I noticed that a fairly significant portion of browser page load was attributable to instantiating a DWN instance (`Dwn.create()`).

Today it takes an average of 835ms

I got curious as to when this had increased since I didn't remember it taking this long the last time I had done rudimentary benchmarking

I found that up until `0.0.26` (Mar 2023) creating a DWN had averaged `220ms` , which had been the case as far back as I tested (Oct 2022)

Two commits in `0.0.25`/`0.0.26` nearly tripled the time (`220` -> `630` ms)
and another in `0.0.29` added an additional 33% (`630` -> `835` ms)

Altogether, it takes nearly 4x longer to instantiate a DWN as a result of these changes made in Mar/Apr.

<img width="1855" alt="Screenshot 2023-08-24 at 9 31 08 AM" src="https://github.com/TBD54566975/dwn-sdk-js/assets/134693/af339233-705b-477d-b5d8-981b2f7ec438">

**Comment by frankhinek** [comment]
@mistermoe found the following `sleep()` calls in `Dwn.open()` and `Dwn.close()`:

https://github.com/TBD54566975/dwn-sdk-js/blob/285036b386a14e354e8c3cebaca6d7d9aabcb1b6/src/store/level-wrapper.ts#L51

https://github.com/TBD54566975/dwn-sdk-js/blob/285036b386a14e354e8c3cebaca6d7d9aabcb1b6/src/store/level-wrapper.ts#L71

Quick testing:
- with `200ms` sleep timers it takes [809ms](url) in a Node environment to `Dwn.create()`
- with `5ms` sleep timers it takes `24ms`
- with `1ms` sleep timers it takes just  `7ms`

**Comment by thehenrytsai** [comment]
This is done by #501.
