### ISSUE TITLE
Implement selective sync

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#486]

**Comment by csuwildcat** [comment]
Liran to consider application of selective sync for propagation pulls.

**Comment by csuwildcat** [comment]
Liran to provide update next week after group chats.

**Comment by pdxjohnny** [comment]
Just FYI, have been working on some IETF SCITT policy engine based patterns for evaluation of GitHub Actions schema based workflows which load data for evaluation leveraging content addressable ontologies.

The goal is that nodes federating will dereference manifests which declare the admission control/ registration policy by which a new data event was accepted to be federated within a particular feed / context.

Nodes can then propagate events by feed / context and leverage existing trust relationships to determine if policy re-evaluation or additional context dependent validation is needed.

**Comment by thehenrytsai** [comment]
This is done.
