### ISSUE TITLE
Use the same level for index as blockstore is using

### ISSUE THREAD

**Issue by 0xzoz** [TBD54566975/dwn-sdk-js#49]
https://github.com/TBD54566975/dwn-sdk-js/blob/98202beeed579628203b45fdaad45583409bd743/src/store/message-store-level.ts#L43-L53

**Comment by thehenrytsai** [comment]
Thanks @mistermoe for investigating.

Won't be possible in the near term because:

> the encoding of values has to be json for search index
and it’s binary for our blockstore
that’s the incompatibility

**Comment by sondreb** [comment]
What about using sublevel capability of `abstract-level`? Maybe that's possible to utilize?

https://github.com/Level/abstract-level#sublevel--dbsublevelname-options
