### ISSUE TITLE
Paramaterize name in message-store-level.ts

### ISSUE THREAD

**Issue by 0xzoz** [TBD54566975/dwn-sdk-js#50]
Calling `searchIndex` twice causes the process to hang, so check to see if the index has already been "opened" before opening it again.

https://github.com/TBD54566975/dwn-sdk-js/blob/98202beeed579628203b45fdaad45583409bd743/src/store/message-store-level.ts#L43-L53

**Comment by Dgarc359** [comment]
As per #55, description of searchIndex behavior is not relevant to this issue. I will be submitting a PR for this soon

**Comment by thehenrytsai** [comment]
Closing this issue as the TODO is already implemented.
