### ISSUE TITLE
Clean up code and make composable

### ISSUE THREAD

**Issue by 0xzoz** [TBD54566975/dwn-sdk-js#51]
Clean this up and likely move it elsewhere (e.g. a different function) so that it can be used elsewhere

https://github.com/TBD54566975/dwn-sdk-js/blob/98202beeed579628203b45fdaad45583409bd743/src/store/message-store-level.ts#L110-L118

**Comment by kriptonian1** [comment]
I would like to work on this

**Comment by thehenrytsai** [comment]
Code no longer exists.
