### ISSUE TITLE
Make `maxDataSizeAllowedToBeEncoded` configurable

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/dwn-sdk-js#515]
Maybe add a config to `Dwn#create`.

**Comment by csuwildcat** [comment]
Is this just so it's easier to change as we settle on something?

**Comment by diehuxx** [comment]
No, more that I don't see why we (contributors to this repo) need to settle on a single value at all. I can imagine developers wanting to tweak it different ways depending on what underlying data store they use.

This isn't a hill I'm trying to die on, just something that crossed my mind.

**Comment by thehenrytsai** [comment]
The theory for maintaining the same constant across different store implementations was to provide developers with consistent expectations, potentially simplifying their code by reducing the number of conditions they need to consider. But this is still just a theory.

**Comment by thehenrytsai** [comment]
Closing this for now due to inaction and unlikely to be visited anytime soon. Can always reopen if need arises.
