### ISSUE TITLE
why not use solid ?

### ISSUE THREAD

**Issue by romainPrignon** [TBD54566975/dwn-sdk-js#52]
https://solidproject.org/

**Comment by cbruguera** [comment]
@romainPrignon can you expand on why Solid and how do you see Decentralized Web Nodes using Solid? How does this integration look like?

**Comment by romainPrignon** [comment]
hey @cbruguera :-)
I don't know all the internals about solid and DWN to give you something usefull.
I was just pointing out that DWN and solid might share the same purpose.

**Comment by csuwildcat** [comment]
Closing, no intent to abandon decentralized personal datastores for a more centralized content server project.
