### ISSUE TITLE
Add range filter support for `dataSize`

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#525]
### Background:
Currently the supported records filter does not have `dataSize`

```ts
export type RecordsFilter = {
  attester?: string;
  recipient?: string;
  protocol?: string;
  protocolPath?: string;
  contextId?: string;
  schema?: string;
  recordId?: string;
  parentId?: string;
  dataFormat?: string;
  dateCreated?: RangeCriterion;
};
```

### Task Details:
Add range filter support for `dataSize`.

We can follow the pattern established by the `dateCreated` filter. But the existing `RangeCriterion` type only supports string, thus some creativity is required to either extend the type, or come up with a new type.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by captain-Akshay** [comment]
i would like to work on this!

**Comment by thehenrytsai** [comment]
Hi @LynxSumit, thanks for your interest in contributing. Added the description above, let us know if you need further info.

**Comment by shobitb** [comment]
@thehenrytsai There's also `RangeFilter` type which takes both string and number `RangeValue`:

https://github.com/TBD54566975/dwn-sdk-js/blob/11caeb4500d1edccff27e78fde96dc9ea4687106/src/types/message-types.ts#L70

Do you still need `RangeCriterion` to support number? Or was there a plan to converge to `RangeFilter` everywhere?

**Comment by shobitb** [comment]
OK, thanks for confirming, @thehenrytsai!  In that case, is maintaining backwards compatibility something to think about? I don't know if there are clients of dwn-sdk-js out there that might be using `RecordsFilter` with `RangeCriterion` type for `dateCreated`.  If yes, then the solution might be to modify as follows:

```
  export type RecordsFilter = {
  attester?: string;
  recipient?: string;
  protocol?: string;
  protocolPath?: string;
  contextId?: string;
  schema?: string;
  recordId?: string;
  parentId?: string;
  dataFormat?: string;
  ** dateCreated?: RangeCriterion|RangeFilter; **
  dataSize?: RangeFilter;
};
```

Thoughts?

**Comment by thehenrytsai** [comment]
@shobitb, it is fine (arguably better off) to break backwards compatibility right now.

**Comment by shobitb** [comment]
@thehenrytsai I've created a PR above for replacing the `dateCreated` with RangeFilter (removing RangeCriterion).
https://github.com/TBD54566975/dwn-sdk-js/pull/553

I can send a separate PR for introducing `dataSize`, or @LynxSumit can work on it as he expressed interest first and things should be more clear after this conversation and the above PR.  @LynxSumit do you want to collaborate on this?

**Comment by EbonyLouis** [comment]
thanks @LynxSumit !, @shobitb I've assigned it to you 🥳
