### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/dwn-sdk-js#526]
there are few typo in the readme.md

![image](https://github.com/TBD54566975/developer.tbd.website/assets/59491379/13d36cfa-7b4c-4f2c-8e32-8c3e3f459868)

- "succesfully" should be "successfully."
- "imposter" should be "impostor."
- "first 10 contributor " should be "first 20 contributor"(as per other readme.md)

# I would like to work on this one
Thanks in advance 😅😅!

**Comment by captain-Akshay** [comment]
@EbonyLouis i asked in the issue in Highlighted to assign it to me so that i could push a PR!🙁🙁

**Comment by EbonyLouis** [comment]
@captain-Akshay I know I'm so sorry a contributor already submitted a PR for it, before I could assign it to you.
