### ISSUE TITLE
No template for issue and pull request in dwn-sdk-js

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/dwn-sdk-js#529]
The repository "developer.tbd.website" contains templates for both issue creation and pull requests. It is recommended to include these templates in this repository as well. Doing so will enhance the clarity and effectiveness of contributions made by other contributors.

Fix :-
it is easy just have to make a similar template for the contributor

**Comment by captain-Akshay** [comment]
would like to work on this issue!!

**Comment by captain-Akshay** [comment]
@angiejones would love to hear your thoughts about this one!

**Comment by angiejones** [comment]
> @angiejones would love to hear your thoughts about this one!

up to this project's maintainer
