### ISSUE TITLE
Normalize Schema and Protocol properties within a PermissionsGrant

### ISSUE THREAD

**Issue by LiranCohen** [TBD54566975/dwn-sdk-js#530]
### Background:
When dealing with `protocol` and `schema` properties across various Interface Methods we normalize the properties into URLs.
Currently the `PermissionsGrant` interface does not normalize this within the provided `PermissionsScope`.

### Task Details:
Normalize the `schema` and `protocol` properties within `PermissionsScope` within the `create` method of the `PermissionsGrant` interface class.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by adarsh-a-tw** [comment]
@LiranCohen  picking this up
