### ISSUE TITLE
Add range filter support for `published` & `datePublished`

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#535]
### Background:
Currently the supported records filter is missing `datePublished`

```ts
export type RecordsFilter = {
  attester?: string;
  recipient?: string;
  protocol?: string;
  protocolPath?: string;
  contextId?: string;
  schema?: string;
  recordId?: string;
  parentId?: string;
  dataFormat?: string;
  dateCreated?: RangeCriterion;
};
```

### Task Details:
Add filter support for `datePublished`.

We can for the most part follow the pattern established by the `dateCreated` filter. But there is one significant difference:

`datePublished` is an optional field, so we need to:
1. Also introduce `published` filter and require it when `datePublished` range filter is specified.
2. We must prevent unauthorized access of reading private date even when `published` filter is set `false`. e.g. Throw error if a query/read is unauthenticated.

**Comment by alanhkarp** [comment]
"We must prevent unauthorized access of reading private date even when published filter is set false. e.g. Throw error if a query/read is unauthenticated."

Do you mean, "Throw an error if a query/read is unauthorized"?

**Comment by thehenrytsai** [comment]
This is now done.
