### ISSUE TITLE
Remove dedicated `handleXyz()` methods in `Dwn` class in favor of the generic `processMessage`

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#563]
### Background:
With the commit of (#554) which uses a clever scheme to provide TS type info, we no longer need dedicated handlers to provide the same type info for developers.

### Task Details:
Remove all `handleXyz()` methods in `Dwn` in favor of just the generic `processMessage()` such as: 

`handleRecordsRead(...)`
`handleRecordsWrite(...)`

### Objective:
No declaration and references of `Dwn`'s `handleXyz()` methods anywhere in codebase, including tests.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by shobitb** [comment]
@EbonyLouis I'll pick this since I have context from my previous PR/issue #549 : )

Thanks!
