### ISSUE TITLE
Create a utility method for creating a DWN compatible timestamp

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#570]
### Background:
When creating a message, there is ability to supply your own timestamp in IOS 8601 format with microsecond precision, but we don't provide a utility method for this.

### Task Details:
Create a utility method for creating a timestamp accepted by DWN.

A potential method signature:

```ts
  /**
   * Creates a UTC ISO-8601 timestamp in microsecond precision accepted by DWN.
   */
  public static createTimestamp(year: number, month: number, day: number, hour: number:, minute: number, second: number, subsecond: number): string {
    ...
  }

```

For implementation reference you can check out [this test utility](https://github.com/TBD54566975/dwn-sdk-js/blob/e5a1a31f973060353654a9cf83d18249a092e515/tests/utils/test-data-generator.ts#L830).

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by Dhoni77** [comment]
picking this up

**Comment by flothjl** [comment]
@Dhoni77  just seeing if you are still wanting to work on this. If not, I'm happy to pick it up! 
@EbonyLouis

**Comment by Dhoni77** [comment]
> @Dhoni77 just seeing if you are still wanting to work on this. If not, I'm happy to pick it up! @EbonyLouis

Hi @flothjl you can pick it👍

**Comment by thehenrytsai** [comment]
This is now done.
