### ISSUE TITLE
Remove circular dependencies 

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/dwn-sdk-js#599]
We ran into a circular dependency issue when trying to update `dwn-sdk-js` version in `dwn-sql-store`. https://github.com/TBD54566975/dwn-sql-store/pull/9. I was able to resolve it quickly with #598.

But, we have plenty of other circular dependencies in `dwn-sdk-js`. They don't seem to be causing immediate problems, but we should resolve them soon since they are hard to debug. Consider using a tool like [madge](https://www.npmjs.com/package/madge) to detect circ dependencies.

**Comment by thehenrytsai** [comment]
This should be done now.
