### ISSUE TITLE
Consider simplifying the SDK by using a singleton for DID Resolver

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#61]
With a singleton, we will not need to pass the DID resolver around in many methods in the SDK.

**Comment by Cxxshyy** [comment]
can look at this as well with guidance#

**Comment by thehenrytsai** [comment]
Haven't thought too deeply about this, but the reason behind filing this issue was seeing many instances of the DID resolver passing down from DWN construction to a lot of classes. But not passing it down also has the downside of hiding this dependency, making it not obvious that the DID resolver is a critical dependency... so I have made up my mind to know if this is really a good direction. So I am going to take this off the "good first issue" list.

But it is not too difficult to implement, an approach to implement this would be:
1. Create a singleton instance in did-resolver.
2. Reference the singleton resolver "when a resolver is not explicitly passed".

**Comment by Cxxshyy** [comment]
i understand the first 2 i think but not the last one what does it mean?

**Comment by thehenrytsai** [comment]
I meant to say "allow updating/changing the singleton instance so tests can mock it.

**Comment by Cxxshyy** [comment]
ok also i cant see where the Didresolver first gets instantiated in the file because from what i can see other files just import the clas and do '''didResolver: DidResolver'''

**Comment by thehenrytsai** [comment]
It is first injected through the `Dwn` constructor, then passed down in a cascading fashion.

**Comment by Cxxshyy** [comment]
ok just to make sure you mean every occurrence of ![image](https://user-images.githubusercontent.com/74113508/197890052-c68f80b4-d197-4f06-b33f-c17bab4a0ca4.png) i just change to a getInstance method from the singleton

**Comment by thehenrytsai** [comment]
Super low pri now, can always reopen if this becomes an issue.
