### ISSUE TITLE
Intermittently hit with validator errors

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#615]
This appears randomly from Vite, with no error thrown in the actual console on the app side:

![image](https://github.com/TBD54566975/web5-js/assets/131786/4f053d5b-a84b-45ae-8c25-37f9bead3f7d)

**Comment by thehenrytsai** [comment]
Are you using released package? Or are you working in the `dwn-sdk-js` itself? If the former, then I don't know why `vite` would randomly not find the file, the file is there, unless it is failing to copy it before starting the server.

**Comment by thehenrytsai** [comment]
Closing as stale. Haven't heard complains similar to this in months. Feel free to reopen or open new issues.
