### ISSUE TITLE
409 Conflict seems to be leaking across users or DWNs, can't tell which

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#616]
I am alternating between storing the string 'Testing' and 'Daniel', and every request is being returned with a 409:

![image](https://github.com/TBD54566975/dwn-sdk-js/assets/131786/456e91e9-3c34-43ad-a3b6-1ebfffac288e)

**Comment by thehenrytsai** [comment]
Can you print out the timestamp of each write?

**Comment by frankhinek** [comment]
@csuwildcat This may be resolved by a bug fix in `@web5/api`.  Should test with an alpha to confirm.

**Comment by thehenrytsai** [comment]
Closing as stale. Haven't heard complains similar to this in months. Feel free to reopen or open new issues.
