### ISSUE TITLE
Add cache support to DidResolver

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/dwn-sdk-js#62]
Add DIDCache to constructor method signature.

https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/did/did-resolver.ts#L9-L17

**Comment by Cxxshyy** [comment]
i'd like to try this out if someone could guide me

**Comment by Cxxshyy** [comment]
yes i think so. 1st i add the resolvers to the local cache using the set method then in the resolve method i add the get function from cache to check whether the resolver is currently residing in cache at that point in time? elt me know if this is correct.

**Comment by thehenrytsai** [comment]
No no, it's not the list of `DidMethodResolver` themselves that need caching, it's the result returned by  the `resolve(...)` call, specfically:

```typescript
const resolutionResult = await didResolver.resolve(did);
```

`resolve(...)` is possibly expensive, so adding a cache in front of it would help with perf. Let me know if this makes more sense now.

**Comment by Cxxshyy** [comment]
oh yes that's what i meant by my explanation but i guess i didn't  convey it great sorry.

**Comment by Cxxshyy** [comment]
#124 aims to tackle this issue

**Comment by Cxxshyy** [comment]
![image](https://user-images.githubusercontent.com/74113508/198318325-a5f30e18-552d-4b33-8576-c92581859641.png)
im now getting this error

**Comment by Cxxshyy** [comment]
although this file hasnt been modified

**Comment by thehenrytsai** [comment]
I think you pulled recently, but you'll also need to do an `npm install` 'coz dependencies have changed.

**Comment by thehenrytsai** [comment]
Addressed by #155.
