### ISSUE TITLE
Add better DID validation

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/dwn-sdk-js#63]
Current requester DID validation uses naive technique. Add better DID validation.

https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/did/did-resolver.ts#L26-L33

Proposed changes in PR https://github.com/TBD54566975/dwn-sdk-js/pull/60. New function `validateDID(did)`:
https://github.com/TBD54566975/dwn-sdk-js/blob/e9b76bc7c45115d4c4577c1369bd46a6da9b64f2/src/did/did-resolver.ts#L26-L30

Function implementation:
https://github.com/TBD54566975/dwn-sdk-js/blob/e9b76bc7c45115d4c4577c1369bd46a6da9b64f2/src/did/did-resolver.ts#L53-L68

**Comment by thehenrytsai** [comment]
Merged.
