### ISSUE TITLE
Figure out if support needed for all W3 verification method properties

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/dwn-sdk-js#64]
Figure out if we need to support ALL verification method properties.

https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/did/did-resolver.ts#L97-L112

**Comment by thehenrytsai** [comment]
I am interpreting this as all the different public key formats, if so, I'd say we will focus on just JWK format for the foreseeable future. With this, we just need to remove this TODO from the code.

**Comment by thehenrytsai** [comment]
PR merged.
