### ISSUE TITLE
What is the incentive for running a node

### ISSUE THREAD

**Issue by dnh33** [TBD54566975/dwn-sdk-js#654]
Why would I waste resources running a node for this network. Are there any financial incentives for securing the network or others data and identities?

**Comment by dnh33** [comment]
How can I trust others on the network if they're not incentivised to do so

**Comment by csuwildcat** [comment]
> Why would I waste resources running a node for this network. Are there any financial incentives for securing the network or others data and identities?

Unlike a blockchain or randomly open IPFS node, your personal datastore only contains your data you've permitted to be there, so the incentive model is: you need to care about yourself.

**Comment by dnh33** [comment]
So I would be centralising my data and pay for a storage for this data, which is then hosted on someone else's hardware or I would have to learn the technical skills so run my own thing at home leaving everything open to attack from the outside on my home network unless I'm some cybersecurity specialist 

This is not viable long term in my opinion and this is why Bitcoin will be the best way to secure your identity (BitcoinSV) and it's all in the original white paper. 

This web5 seems like a bit of a stretch to try and solve a problem that has already been solved 15 years ago.

It's way too late now for this to become relevant in the long run.

**Comment by dnh33** [comment]
And please, don't give the EU the idea that I should log into my browser using my "decentralised identity"

**Comment by LiranCohen** [comment]
>So I would be centralising my data and pay for a storage for this data, which is then hosted on someone else's hardware or I would have to learn the technical skills to run my own thing at home leaving everything open to attack from the outside on my home network unless I'm some cybersecurity specialist.

The way DWNs work is that there is a local node running in the browser or via an agent app, as well as one or multiple remote nodes that are listed in the user's DID. Each browser context can be it's own DWN. The individual DWNs initiate a sync between the local and remote nodes to replicate the data and arrive at a single state in an eventually consistent manner.

So you would more than likely rely on a service provider to run your public facing ingress/propagation, as you mention average users aren't gurus to run high availability services. But you are not limited to that, nor are you limited to a single service provider.

![dwn-topology](https://github.com/TBD54566975/dwn-sdk-js/assets/2191517/7da1f3cc-05a0-4c32-aa6e-1dcd4944fe6e)

I hope that helps clear up the mental model of how DWNs work a bit more.
