### ISSUE TITLE
Add cache support to avoid costly validation of the same signature

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/dwn-sdk-js#66]
Add logic to prevent validating duplicate signatures 

https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/jose/jws/general/verifier.ts#L14-L44

**Comment by thehenrytsai** [comment]
We've implemented an [in-memory cache](https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/utils/memory-cache.ts) that can be used.

**Comment by thehenrytsai** [comment]
Thanks again @flothjl!
