### ISSUE TITLE
Simplify the filters used for `EventsQuery` and `EventsSubscribe`

### ISSUE THREAD

**Issue by LiranCohen** [TBD54566975/dwn-sdk-js#663]
Currently the filters used for `EventsQuery` and `EventsSubscribe` which will primarily be used for `selective sync` support many different filters.  However this adds a level of complexity that may not be currently needed.

Reduce the filters to what we need for the MVP of `selecive sync` and add additional filters later on as needs arise with more specific behavior.

The most important filter would be `protocol` which would allow DWNs to selectively sync all of the relevant data associated with a particular protocol.

This specific ask may require additional enhancements to truly sync all the data a user may need to support a protocol such as Permissions, ProtocolConfgires and Records.

**Comment by thehenrytsai** [comment]
This is done!
