### ISSUE TITLE
Replace verificationMethod checks with JSON Schema based validation (JsonWebKey2020)

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/dwn-sdk-js#67]
Replace with JSON Schema based validation for `JsonWebKey2020`. More info about the `JsonWebKey2020` type can be found here: https://www.w3.org/TR/did-spec-registries/#jsonwebkey2020

https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/jose/jws/general/verifier.ts#L66-L73

**Comment by flothjl** [comment]
[WIP PR](https://github.com/TBD54566975/dwn-sdk-js/pull/121)

**Comment by flothjl** [comment]
Hey there! 👋 
Big apologies - I goofed for accidentally marking my PR as `requesting review` first - I have changed it to a draft!

**Comment by flothjl** [comment]
In looking at verification method [spec](url) it looks like `controller` is required, so I went ahead and updated current jws tests where verification methods are defined to include `controller` property. Any thoughts on this?
