### ISSUE TITLE
Replace verificationMethod checks with JSON Schema based validation (publicJwk)

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/dwn-sdk-js#68]
Replace with JSON Schema based validation for `publicJwk`. More info about the `publicJwk` property can be found here: https://www.w3.org/TR/did-spec-registries/#publicJwk 

https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/jose/jws/general/verifier.ts#L74-L84

**Comment by flothjl** [comment]
@thehenrytsai interested in your thoughts on depth of validation in my first pass at this. Initially started with basic checks for required fields, but then decided might be valuable to validate there is no private properties and that the curve is valid for a keytype. 

Thanks!

**Comment by thehenrytsai** [comment]
@flothjl, thanks for tackling this, I've merged in your PR! 🎆 🍾 🎊
