### ISSUE TITLE
Export all types that are referenced by all exported types

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#686]
Currently there are types referenced by exported types that are not explicitly exported which is not friendly for developers from documentation point of view.

Run `npx typedoc --validation --entryPoints src/index.ts` agains the repo and look for:

```
[warning]... defined in... but not included in the documentation
```

And remove all those instances by exporting the type referenced.

**Comment by aniketh-varma** [comment]
.take
