### ISSUE TITLE
Declare proper typing for `includeCriteria` and `excludeCriteria` in MessageStore and MessageStoreLevel

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/dwn-sdk-js#69]
Change type of `query`

https://github.com/TBD54566975/dwn-sdk-js/blob/fcea84929e12dd3e3ef0e8866b0e592a025786fa/src/store/message-store.ts#L32-L34

**Comment by thehenrytsai** [comment]
method signature is now update as:
https://github.com/TBD54566975/dwn-sdk-js/blob/ee5beaeb99b2cf5c796dde520f52d6ee47b9ef7b/src/store/message-store.ts#L34

**Comment by thehenrytsai** [comment]
`excludeCriteria` is no longer needed thus removed.
