### ISSUE TITLE
Add `lowS: false` flag to secp256k1.ts `verify`

### ISSUE THREAD

**Issue by theisens** [TBD54566975/dwn-sdk-js#714]
As has been noted in the [@web5/crypto package](https://github.com/TBD54566975/web5-js/blob/91d52aaa9410db5e5f7c3c31ebfe0d4956028496/packages/crypto/src/primitives/secp256k1.ts#L779), support for low-s signatures is not guaranteed by major KMS providers. I have personally run into this issue when using Azure keys for signing. Requesting that the `lowS` flag be set to `false` by default for verification of secp256k1 signatures, as it is in @web5/crypto package.

**Comment by OR13** [comment]
jfyi, if you are not sure which type of signature you are being handed, and you require lower s, you can always normalize to lower s before calling verify.

**Comment by aniketh-varma** [comment]
.take
