### ISSUE TITLE
Add input property validation for all message `create()` methods

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#78]
Add input validation for all message `create()` methods by reusing the JSON schema already being used during message processing: https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/validation/validator.ts#L20

Example create method needing update:
https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/interfaces/collections/messages/collections-write.ts#L26

**Comment by virajjiwane** [comment]
Hi, @thehenrytsai I am just starting to contribute to open source projects. and I would like to work on this issue.
