### ISSUE TITLE
Search index appear to be broken for some special characters

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#80]
After a lot of confusion testing CollectionsWrite, it appears that search index appear to be broken for some special characters. For instance:

`dataFormat` with forward slash: `application/json`
`recordId` with hyphens: `f227a18b-0d2f-4b83-b7c6-1b09e04d98b9`

Running tests against the `henrytsai/collections-write-2` branch: `npm run test:node` will demonstrate the problem.

**Comment by mistermoe** [comment]
@thehenrytsai [here's](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/store/message-store-level.ts#L165-L167) where you can add additional characters to exclude during tokenization
