### ISSUE TITLE
Fix Typo for Code of Conduct in Contributing.MD Getting Started Section

### ISSUE THREAD

**Issue by taniashiba** [TBD54566975/dwn-sdk-js#824]
# Fix Typo for Code of Conduct in Contributing.MD Getting Started Section

## 🚀 Goal
We want to ensure all of our documentation don't have mistakes. A community member noticed a small typo to a link in our Contributing.MD file, and this issue is to resolve it.

## 🤝 How You Can Contribute
We've broken it down into what typo to address and where.

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Visit dwn-sdk-js [Contributing.MD ](https://github.com/TBD54566975/dwn-sdk-js/blob/main/CONTRIBUTING.md)
2. Scroll down to [How You Can Get Started](https://github.com/TBD54566975/dwn-sdk-js/blob/main/CONTRIBUTING.md#heres-how-you-can-get-started) in Hacktoberfest section
3. Update Code of Conduct.MD link (see attached screenshot) ![Image](https://github.com/user-attachments/assets/1a52d431-4a76-460e-8bcf-c51ae7dbfcba)

4. Make no other changes.

## 🌟 Resources
- [dwn-sdk-js Contributing.MD](https://github.com/TBD54566975/dwn-sdk-js/blob/main/CONTRIBUTING.md)
- [Blog, Developer Website](https://developer.tbd.website/blog)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by shawaiz-khan** [comment]
.take

**Comment by aniketh-varma** [comment]
.take

**Comment by shawaiz-khan** [comment]
Kindly mark this as hacktoberfest accepted 😊
