### ISSUE TITLE
Update resolver to GA version

### ISSUE THREAD

**Issue by mahoekst** [TBD54566975/dwn-sdk-js#83]
The GA version of the resolver (ION) is https://discover.did.msidentity.com/1.0/identifiers/did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w

Sample did is the first record on ION from Henry :)

**Comment by thehenrytsai** [comment]
Wow! Didn't realize there is a GA endpoint, thanks for the heads up!!

**Comment by thehenrytsai** [comment]
Updated.
