### ISSUE TITLE
Allow inbound callers to decide if they want to wait for Handler responses

### ISSUE THREAD

**Issue by csuwildcat** [TBD54566975/dwn-sdk-js#94]
Due to the fact Handlers can be set outside of a caller's awareness/expectations, make it possible too pass a flag that indicates whether or not the caller wants to wait for Handler responses that may significantly delay the completion of the request over synchronous connection protocols. Make the default false, with return happening without holding for Handlers.

**Comment by thehenrytsai** [comment]
No longer applicable.
